version: '3'
services:
  mysql_db:
   image: mariadb
   ports:
   - "4306:3306"
   environment:
    MYSQL_USER: canopy
    MYSQL_PASSWORD: canopy
    MYSQL_DATABASE: canopy
    MYSQL_ROOT_PASSWORD: canopy

  postgres_db:
   image: postgres:9.6
   ports:
   - "6432:5432"
   environment:
    POSTGRES_PASSWORD: canopy
    POSTGRES_USER: canopy
    POSTGRES_DB: canopy

  web:
    build: .
    ports:
     - "8080:80"
    depends_on:
     - mysql_db
     - postgres_db
    volumes:
     - .:/var/www/html
    tty: true