version: '3'
services:
  mysql_db:
   image: mariadb
   ports:
   - "4306:3306"
   environment:
    MYSQL_USER: phpwebsite
    MYSQL_PASSWORD: phpwebsite
    MYSQL_DATABASE: phpwebsite
    MYSQL_ROOT_PASSWORD: phpwebsite

  postgres_db:
   image: postgres
   ports:
   - "6432:5432"
   environment:
    POSTGRES_PASSWORD: phpwebsite
    POSTGRES_USER: phpwebsite
    POSTGRES_DB: phpwebsite

  web:
    build: .
    ports:
     - "8080:80"
    depends_on:
     - mysql_db
     - postgres_db
    volumes:
     - .:/var/www/html
    tty: true