version: '3'
services:
  mysql_db:
   image: mariadb
   ports:
   - "4306:3306"
   environment:
    MYSQL_USER: canopy
    MYSQL_PASSWORD: canopy
    MYSQL_DATABASE: canopy
    MYSQL_ROOT_PASSWORD: canopy

  postgres_db:
    build:
      context: .
      dockerfile: ./docker_postgres/Dockerfile
    ports:
      - "6432:5432"
    environment:
      PGDATA: /var/lib/pgsql/data
    tty: true

  web:
    build:
      context: .
      dockerfile: ./docker_web/Dockerfile
    ports:
     - "8080:80"
    depends_on:
     - mysql_db
     - postgres_db
    volumes:
     - .:/var/www/html
    tty: true
